//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class GoodsReceipts
    {

        [Key]        
        public int GoodsReceiptID { get; set; }
        [ForeignKey(nameof(PurchaseOrders))]
        public int PurchaseOrderID { get; set; }
        [ForeignKey(nameof(Warehouses))]
        public int WarehouseID { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual PurchaseOrders PurchaseOrders { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
