//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class GoodsIssues
    {
        [Key]
        public int GoodsIssueID { get; set; }
        [ForeignKey(nameof(SalesOrders))]
        public int SalesOrderID { get; set; }
        [ForeignKey(nameof(Warehouses))]
        public int WarehouseID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual SalesOrders SalesOrders { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
