//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class InventoryCounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryCounts()
        {
            this.InventoryCountItems = new HashSet<InventoryCountItems>();
        }

        [Key]
        public int InventoryCountID { get; set; }
        [ForeignKey(nameof(Warehouses))]
        public int WarehouseID { get; set; }
        public Nullable<System.DateTime> CountDate { get; set; }
        public string ResponsiblePerson { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryCountItems> InventoryCountItems { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
