//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InventoryCountItems
    {
        [Key]
        public int InventoryCountItemID { get; set; }
        public int InventoryCountID { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> SystemQuantity { get; set; }
        public Nullable<decimal> CountedQuantity { get; set; }
        public Nullable<decimal> Difference { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual InventoryCounts InventoryCounts { get; set; }
        public virtual Products Products { get; set; }
    }
}
