//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseDbEntities : DbContext
    {
        public WarehouseDbEntities(string connectionString)
            : base(string.Format(@"metadata=res://*/Models.ModelWarehouse.csdl|res://*/Models.ModelWarehouse.ssdl|res://*/Models.ModelWarehouse.msl;provider=System.Data.SqlClient;provider connection string='{0}'", connectionString))
        {
        }

        //public WarehouseDbEntities()
        //: base()
        //{
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<GoodsIssues> GoodsIssues { get; set; }
        public virtual DbSet<GoodsReceipts> GoodsReceipts { get; set; }
        public virtual DbSet<InventoryCountItems> InventoryCountItems { get; set; }
        public virtual DbSet<InventoryCounts> InventoryCounts { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Movements> Movements { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<PurchaseOrderItems> PurchaseOrderItems { get; set; }
        public virtual DbSet<PurchaseOrders> PurchaseOrders { get; set; }
        public virtual DbSet<SalesOrderItems> SalesOrderItems { get; set; }
        public virtual DbSet<SalesOrders> SalesOrders { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
