//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Movements
    {
        [Key]
        public int MovementID { get; set; }
        [ForeignKey(nameof(Products))]
        public int ProductID { get; set; }
        public Nullable<int> FromLocationID { get; set; }
        public Nullable<int> ToLocationID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string MovementType { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<System.DateTime> MovementDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Locations Locations { get; set; }
        public virtual Locations Locations1 { get; set; }
        public virtual Products Products { get; set; }
    }
}
