//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PurchaseOrderItems
    {
        [Key]
        public int PurchaseOrderItemID { get; set; }
        [ForeignKey(nameof(PurchaseOrders))]
        public int PurchaseOrderID { get; set; }
        [ForeignKey(nameof(Products))]
        public int ProductID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual PurchaseOrders PurchaseOrders { get; set; }
    }
}
